[package]
name = "quick-layout"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
quick-core = { path = "../quick-core" }
quick-style = { path = "../quick-style" }
taffy = { workspace = true }
slotmap = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
