[package]
name = "quick-render"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
quick-core = { path = "../quick-core" }
quick-style = { path = "../quick-style" }
bumpalo = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
fontdue = "0.9.4"

[features]
default = []
skia = ["dep:skia-safe"]

[dependencies.skia-safe]
workspace = true
optional = true
