[package]
name = "quick-render"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
quick-core = { path = "../quick-core" }
quick-style = { path = "../quick-style" }
bumpalo = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
fontdue = "0.9.4"
kurbo = { workspace = true, optional = true }
peniko = { workspace = true, optional = true }
vello = { workspace = true, optional = true }
wgpu = { workspace = true, optional = true }

[features]
default = ["vello"]
vello = ["dep:vello", "dep:wgpu", "dep:kurbo", "dep:peniko"]
