[package]
name = "quick-window"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
quick-core = { path = "../quick-core" }
quick-render = { path = "../quick-render" }
winit = { workspace = true }
raw-window-handle = { workspace = true }
softbuffer = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
vello = { workspace = true, optional = true }
wgpu = { workspace = true, optional = true }
pollster = { workspace = true, optional = true }

[features]
default = ["vello"]
vello = ["dep:vello", "dep:wgpu", "dep:pollster", "quick-render/vello"]
